/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: imwolfgang (https://sketchfab.com/imwolfgang)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/major-mana-potion-407e0fc4e71143398655884eff18aef3
Title: Major Mana Potion
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Potion(props) {
  const { nodes, materials } = useGLTF('/models/major_mana_potion.glb')

  const modelRef = useRef()
  useFrame(() =>{
    modelRef.current.rotation.y += 0.01
  })

  return (
    <group {...props} dispose={null} scale={[3,3,3]} position={[0,0,0]} ref={modelRef}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={materials.Liquid}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.Gemstone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials['Metal.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.Glass}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/major_mana_potion.glb')